### PR TITLE
Fix encoding problem in cryptoNews()

### LINKED ISSUE #42: Fix encoding problem
the problem with cryptoNews() in crypto.js

### PR DESCRIPTION
**Pull request by yaroshchuk8**
Cloeses #42

### CODE REVIEW

File: src/promised.js [hunk 1]
```diff
@@ -43,10 +43,29 @@ const promiseSpawn = (lang, path) => new Promise((resolve, reject) => {
...
+  });
+}
+
 module.exports = {
   question,
   getRequest,
   postRequest,
   promiseSpawn,
   errorWrapper,
+  escapeChars,
```
Comment (akaeyuhi) [inline src/promised.js]: You don`t need to export this hash-table

File: src/promised.js [hunk 2]
```diff
@@ -43,10 +43,29 @@ const promiseSpawn = (lang, path) => new Promise((resolve, reject) => {
...
   func(...args).catch(handleError);
 
+const escapeChars = { lt: '<', gt: '>', quot: '"', apos: '\'', amp: '&' };
+
+function decodeString(str) {
+  return str.replace(/&([^;]+);/g, (entity, entityCode) => {
+    let match;
+    if (entityCode in escapeChars) {
+      return escapeChars[entityCode];
+    } else if (entityCode.match(/^#x([\da-fA-F]+)$/)) {
```
Comment (akaeyuhi) [inline src/promised.js]: Resused code, you can put regex in a variables, or an array(better choice)

**Review by akaeyuhi — APPROVED** [review]
